### ISSUE TITLE
Support AVC depacketizer

### ISSUE THREAD

**Issue by debiandebiandebian** [pion/rtp#107]
## Summary

The current implementation enforces `Annex B` packaging. If each `NALU` should be picked up for
- repacking it into `AVC` for `Matroska` container, or
- checking if all key frame elements (i.e., `SPS` + `PPS` + `IDR`) are present in an aggregate `RTP` packet,

another iteration based on start code should be done. `AVC` packaging is inherently good for locating individual elements, and giving another payloader does not break anything.

## Motivation

Same as above.

## Describe alternatives you've considered

It would be best to return a slice of `NALU`s if possible.

**Comment by Sean-Der** [comment]
We could give `H264Payloader` a `IsAVC bool` key, and then the Payloader could take different paths.

I think this would be a pretty easy change! Thanks for requesting @debiandebiandebian if you are interested in contributing happy to help

**Comment by debiandebiandebian** [comment]
The title was misleading. I meant `H264Packet`, not `H264Payloader`. So, I was talking about `RTP` depacketizer. But, I suppose you catch it right.

Come to think of it, it would be difficult to implement. For example, the first packet of fragmentation units does not tell anything about the entire `NALU` length.

**Comment by Sean-Der** [comment]
Oh yea, I support that as well! Since this isn't an API breaking change I would love to take it

**Comment by debiandebiandebian** [comment]
The reason why I thought it's difficult to implement was
- the entire `NALU` length is unknown until the final [`FUs`](https://tools.ietf.org/html/rfc6184#section-5.8) packet is received, and
- `samplesbuilder` spits out the result immediately for each `RTP` input. 

It was unclear to me how we go back to the first result, and re-write the length portion already given to the user.

But, this trick looks good to me:
- `return []byte{}` for non-final `FUs` packets, otherwise
- aggregate & return the result with preceding `NALU` length.

**Comment by debiandebiandebian** [comment]
If you're fine with the direction above, I would love to give it a shot.

**Comment by Sean-Der** [comment]
Yes! Please make a PR, happy to help however I can :)

**Comment by debiandebiandebian** [comment]
@Sean-Der Oops, I didn't think you would merge it right away.

I want to point out one important pitfall from this PR. Any existing application depending on this module would break if
- a single `H264Packet` instance is accessed from multiple goroutines.

Back then, we had no instance fields, so users might have used a single instance from all over the places. In this case, `fuaBuffer` will be stuffed with two or more different `RTP` stream packets.

**Comment by debiandebiandebian** [comment]
If `Pion` can't afford such risk, you might want to revert this PR.

**Comment by debiandebiandebian** [comment]
Thanks for helping me through this issue, @Sean-Der !
