### ISSUE TITLE
Support AVC depacketizer breaks pion/webrtc

### ISSUE THREAD

**Issue by robin-raymond** [pion/rtp#127]
related to PR:
https://github.com/pion/rtp/pull/110

@debiandebiandebian There is an issue with this PR will break pion/webrtc h264writer_test.go

The reason is because the writer uses:
````
	data, err := (&codecs.H264Packet{}).Unmarshal(packet.Payload)
````

Basically, it creates a H264Packet object on the fly to unmarshal to... but the unit test first writes the h264 FUA START, then an H264 FU END packet, but the first packet unmarshal returns data array with 0 content, the second only returns the END data but not the contents in fuaBuffer because it's been discarded between the previous write.

I'm uncertain the expected fix. I think the H264 packet object be reused in the webrtc h264 writer until the close is called to ensure any buffering in the fuaBuffer is preserved, but I worry about the side effects.

cc: @Sean-Der

**Comment by robin-raymond** [comment]
@debiandebiandebian if you can confirm that webrtc writer needs to be fixed as described above then I'll submit a patch to webrtc with that fix.

**Comment by robin-raymond** [comment]
I think the fix is this:
https://github.com/pion/webrtc/pull/1801/files

Only changes in this file are related to this issue:
pkg/media/h264writer/h264writer.go

**Comment by debiandebiandebian** [comment]
@robin-raymond You're right. My PR would break this case. Re-using a `H264Packet` is necessary.

**Comment by robin-raymond** [comment]
Thank you! I'll leave this issue open until the pion/webrtc fix is merged. Then I will close this issue.

**Comment by debiandebiandebian** [comment]
This is an off-topic, but can you educate me where `h264writer` is actually used? I can't find any in `pion/webrtc`.

**Comment by robin-raymond** [comment]
I'm uncertain. I just wanted the unit tests to pass to fix other webrtc issues. I am guessing it's in pion/ion-avp or pion/ion-sfu?

**Comment by debiandebiandebian** [comment]
Thanks for your time. I should have checked other dependencies before merging this PR. =/
