### ISSUE TITLE
Please revert switch to v2

### ISSUE THREAD

**Issue by jech** [pion/rtp#129]
Commit 863e8351e01da61813308c8689c2aea684402450 updates the package version to v2.  This causes a lot of churn for no good reason, since commit 6b516fba426bbd973d1fef43de8878156056160e merely removes some fields that nobody is using anyhow (that's why they're being removed).

An alternative would be to revert both commits.

If reverting this commit is not possible, then we need an update to pion/webrtc ASAP, since the samplebuilder takes a v1 packet.

**Comment by aler9** [comment]
I added the v2 version since:

* The removal of deprecated fields (`PayloadOffset` and `Raw` in this case) is one of the reasons listed in the [Golang blog](https://blog.golang.org/v2-go-modules) to perform an update to a major version, doesn't matter if the fields are seldom used

* The author [clearly stated](https://github.com/pion/rtp/pull/119) that changes are part of a v2 plan

If there's the need of sticking to a v1 for the time being (since the main maintainer is currently unavailable), an alternative solution consists in moving changes into a dedicated branch.

**Comment by at-wat** [comment]
In my personal opinion, it's better not to hesitate to bump major version if necessary.
But, if there are other possible breaking changes, it would be better to do them at once before bumping the major version.

**Comment by jech** [comment]
@at-wat I agree. The problem here is that switching to v2 put pion/rtc and pion/webrtc out of sync — it was no longer possible to link a recent webrtc against a recent rtp, which forced some git gymnastics if you wanted to tweak rtc.  Just like you, I have no objection to major version changes if they are necessary and all dependencies are updated in a timely manner.

**Comment by Sean-Der** [comment]
If we upgraded `webrtc`, `srtp` and `interceptor` to `github.com/pion/rtp/v2` would that unblock you @jech?

I am fine doing the work to make that upgrade! Would rather move forward the undo contributions.

**Comment by jech** [comment]
This one is not blocking me right now, it just prevents me from contributing to pion/rtp: since any contribution I make will be done to a version that I cannot use, I'd need to maintain my own private branch and do some creative replacing in the modules, which is just not worth the hassle.

The one that's a hard blocker is https://github.com/pion/webrtc/pull/1874, where my bug fixes got into a version that I cannot use due to a broken samplebuilder.  The only solutions I can see is to maintain my own samplebuilder that's not broken, or to stop using the samplebuilder.  This has been broken for over a month not, so it's not just a temporary fluke.

**Comment by Sean-Der** [comment]
I created a `v0` branch and will be cherry-picking changes for now.

I attempted to upgrade pion/webrtc to pion/rtp@v2 but it would be a breaking change. So we need to wait until pion/webrtc@v4
