### ISSUE TITLE
mtu checking code consistency

### ISSUE THREAD

**Issue by wangziyangyu** [pion/rtp#156]
Since `mtu` is unsigned, we should change `mtu <= 0` to `mtu == 0`.  Code in `codecs/g722_packet.go` did use `==`. 

code in `codecs/g711_packet.go`:

```go
func (p *G711Payloader) Payload(mtu uint16, payload []byte) [][]byte {
	var out [][]byte
	if payload == nil || mtu <= 0 {
		return out
	}
        ...
}
```

code in `codecs/g722_packet.go`:

```go
func (p *G722Payloader) Payload(mtu uint16, payload []byte) [][]byte {
	var out [][]byte
	if payload == nil || mtu == 0 {
		return out
	}
       ...
}
```

**Comment by Sean-Der** [comment]
Hi @wangziyangyu 

That makes sense to me! This ends up being a `JEQ` vs `JLS`, so could make a difference?

Would you mind opening a PR?

thanks!
