### ISSUE TITLE
Parse RFC 5285 extensions

### ISSUE THREAD

**Issue by maxhawkins** [pion/rtp#17]
## Summary

Implement [RFC 5285](https://tools.ietf.org/html/rfc5285) RTP header extensions directly in rtp.Packet.

## Motivation

This will allow us to read and write RFC 5285 formatted extensions like abs-sendtime, rtp-audio-level, and video-orientation.

**Comment by maxhawkins** [comment]
It might make sense to get rid of the `Header bool` flag at the same time. If the Header struct contains an extension then Marshal should set it automatically.

**Comment by maxhawkins** [comment]
Sketching an API here:

```go
p := Packet {
	Header: Header{
		Extensions: []Extension {
			{
				ID: 1,
				Payload: payload1,
			},
			{
				ID: 2,
				Payload: payload2,
			},
		},
	},
}
```

Something like this would work for RFC 5285 packets. Not yet sure what to do for packets with a different ExtensionProfile...

**Comment by maxhawkins** [comment]
Maybe useful to add a helper function like `GetExtension(uint8)` also

```go
var a AbsSendTime
payload := pkt.GetExtension(1)
a.Unmarshal(payload)
```

**Comment by maxhawkins** [comment]
Because the identifier 0 is reserved in RFC 5285 maybe we can use it for packets with a different extension profile.

```go
p := Packet {
	Header: Header{
		ExtensionProfile: 0x1234, // not 0xBEDE
		Extensions: []Extension {
			{
				ID: 0,
				Payload: payload1,
			},
		},
	},
}
```

If you want to write a packet with the ExtensionProfile 0x1234 just put the payload in the Extensions array with ID == 0.

**Comment by maxhawkins** [comment]
On second thought, maybe better to use a map:

```go
type Extensions map[int][]byte

type Header struct {
	...
	Extension Extensions
}

p := Packet {
	Header: Header{
		Extensions: Extensions {
			1: payload1,
			2: payload2,
		},
	},
}
```

One caveat: I'm not sure if it's defined in the spec what happens if two extension payloads are returned with the same ID. Need to look into that before going this direction.

**Comment by maxhawkins** [comment]
[Section 4.1](https://tools.ietf.org/html/rfc5285#section-4.1)
```
Each distinct extension MUST have a unique ID.
```

I think that means we can go ahead with the map-based API. Each extension id can only be used once.

**Comment by maxhawkins** [comment]
A `SetExtension()` counterpart to `GetExtension()` would be nice so you don't have to reach into the Header.

```go
a := AbsSendTime(time.Now())
extdata, _ := a.Marshal()
pkt.SetExtension(1, extdata)

(...)

var a AbsSendTime
extdata := pkt.GetExtension(1)
a.Unmarshal(extdata)

```

**Comment by adwpc** [comment]
I really need this feature to do `transport-cc` on `ion`.
I aslo need `pion/webrtc` `pion/sdp` to support extmap: 

RFC:
https://tools.ietf.org/html/draft-holmer-rmcat-transport-wide-cc-extensions-01#page-3
https://webrtc.org/experiments/rtp-hdrext/transport-wide-cc-02/
https://tools.ietf.org/html/rfc8285#page-9

Code:
https://chromium.googlesource.com/external/webrtc/+/HEAD/modules/rtp_rtcp/include/rtp_rtcp_defines.h#51

TransportSequenceNumber and TransportSequenceNumberV2
https://chromium.googlesource.com/external/webrtc/+/HEAD/modules/rtp_rtcp/include/rtp_rtcp_defines.h#51
https://chromium.googlesource.com/external/webrtc/+/HEAD/modules/rtp_rtcp/source/rtp_header_extensions.h#93
https://chromium.googlesource.com/external/webrtc/+/HEAD/modules/rtp_rtcp/source/rtp_header_extensions.cc#235

**Comment by adwpc** [comment]
https://github.com/pion/sdp/issues/28

**Comment by Sean-Der** [comment]
We support both RFC 3550 and RFC 8285

We also support abs-sendtime, audiolevel and transport-cc today.
