### ISSUE TITLE
GoDoc broken due to symlinked LICENSE

### ISSUE THREAD

**Issue by database64128** [pion/rtp#231]
The [GoDoc](https://pkg.go.dev/github.com/pion/rtp) page currently displays "Documentation not displayed due to license restrictions.", because it does not follow symlinks. Before https://github.com/golang/go/issues/40586 gets resolved, it's probably better to have LICENSE as an actual file.

**Comment by at-wat** [comment]
### ref
- https://github.com/pion/.goassets/issues/169

**Comment by stv0g** [comment]
Fixed

**Comment by stv0g** [comment]
We only need to tag a new version
