### ISSUE TITLE
Fix `rtp.Header.PayloadOffset` for extensions

### ISSUE THREAD

**Issue by kixelated** [pion/rtp#5]
Okay, while digging into why this change causes `pions/webrtc` unit tests to hang, I found a bug. `Header.PayloadOffset` has a different value depending on if `Marshal` or `Unmarshal` was used.

For `Unmarshal` it will be set to the offset after the optional extension header/payload.
For `Marshal` it will be set to the offset before the optional extension header/payload.

I'm not sure which is right. There's also a 3rd option where the offset should be between the extension header and payload, if you're actually supposed to encrypt the extension payload. It's late so I'm not going to bother reading the spec juuuust yet.

At least I'm feeling pretty vindicated trying to remove the field...

_Originally posted by @kixelated in https://github.com/pions/rtp/pull/3#issuecomment-464321478_

**Comment by Sean-Der** [comment]
I am :+1: on removing it!

I don't think anyone is really doing math on these things either. They are just grabbing raw and sending them off OR they are building samples.

**Comment by wdouglass** [comment]
seconded -- this field should be removed (are we using it anywhere?)

**Comment by Sean-Der** [comment]
PayloadOffset no longer exists! was removed in 6b516fba426bbd973d1fef43de8878156056160e
