### ISSUE TITLE
Fix TransportCCExtension and AudioLevelExtension to work with new API introduced by #56

### ISSUE THREAD

**Issue by at-wat** [pion/rtp#65]
By #56, extension ID and length is handled by packet marshaler.
But TransportCCExtension and AudioLevelExtension are still handling ID/length as a first byte of extension data. It makes first byte of the extension duplicated.

I noticed this broke AbsSendTimeExtension and fixed in https://github.com/pion/rtp/pull/62.
I think TransportCCExtension and AudioLevelExtension need same fix.

**Comment by at-wat** [comment]
FYI @tarrencev @adwpc

**Comment by adwpc** [comment]
> FYI @tarrencev @adwpc

@at-wat Thanks
fix:
https://github.com/pion/rtp/pull/67

**Comment by at-wat** [comment]
fixed by #67 and #68
