### ISSUE TITLE
Remove Header.PayloadOffset and Packet.Raw

### ISSUE THREAD

**Issue by Sean-Der** [pion/rtp#90]
We have duplication of data `Raw`/`PayloadOffset` and `Payload`.

We need to drop these fields so we have a less fragile API

**Comment by ffmiyo** [comment]
@Sean-Der  Is `Header.PayloadOffset` a must go? It is needed during unmarshal to split between header and payload.  
An alternative is to return as Int from `Header.Unmarshal()`.
