### ISSUE TITLE
Add a method to get `Header.Extension` id array

### ISSUE THREAD

**Issue by ocean2811** [pion/rtp#94]
## Summary
Base rtp@1.6.1
I need a new methon to get all extension ID.
code maybe like this:
`
func (h *Header) GetExtensionIDs(id uint8) []uint8 {
	if !h.Extension {
		return nil
	}

	ids := make([]uint8, len(h.Extensions))
	for _, extension := range h.Extensions {
		ids = append(ids, extension.id)
	}
	return ids
}
`

## Motivation

I try to get all extension ID , because I need know which id that I can read.

## Describe alternatives you've considered
-

## Additional context
-

**Comment by Sean-Der** [comment]
Hey @ocean2811 

This would be a great addition! If you can make a PR with tests I am happy to merge this.

thanks :)
